
platform :ios, '8.0'

inhibit_all_warnings!

target 'iReader' do
    
    pod 'SVProgressHUD', '2.1.2'
    pod 'Masonry', '0.5.3'
    pod 'ZipArchive', '~> 1.4.0'
    pod 'DTCoreText', '1.6.20'
    pod 'FLEX', '~> 2.0', :configurations => ['Debug']

end

